apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # PersistentVolumeClaim name
  name: host-pvc
spec:
  volumeName: host-pv # need same name exact PersistentVolume name
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi