apiVersion: apps/v1
kind: Deployment
metadata:
  name: permalist-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: permalist-app
  template:
    metadata:
      labels:
        app: permalist-app
    spec:
      containers:
        - name: permalist-app
          image: rimra/permalist:v1
          ports:
            - containerPort: 8080
          env:
            # from secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            # from configmap
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB

---
apiVersion: v1
kind: Service
metadata:
  name: permalist-app-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: permalist-app
