version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - permalist-app-net

  permalist-app:
    build: .
    image: permalist-app:v1.0
    container_name: permalist-app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - permalist-app-net

volumes:
  db-data:

networks:
  permalist-app-net:
